version: "3.7"
services:
  colossus:
    restart: always
    build: ./
    image: nickest14/colossus:latest
    environment:
      - TYPE=api
    env_file:
      - ./docker.env
    networks:
      - colossus
    ports:
      - "3001:3000"
  colossus-worker:
    restart: always
    build: ./
    image: nickest14/colossus:latest
    environment:
      - TYPE=worker
    env_file:
      - ./docker.env
    networks:
      - colossus
  colossus-beat:
    restart: always
    build: ./
    image: nickest14/colossus:latest
    environment:
      - TYPE=beat
    env_file:
      - ./docker.env
    networks:
      - colossus
    command: >
      /bin/sh -c "./app task tasks:period_tasks"
  db:
    restart: always
    image: postgres:11.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nick
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=colossus
    networks:
      - colossus
    ports:
      - "5433:5432"
  redis:
    restart: always
    image: redis:5.0.9-buster
    volumes:
      - redis-data:/data
    networks:
      - colossus
    ports:
      - "6380:6379"

networks:
  colossus:
    driver: bridge
    
volumes:
  db-data:
  redis-data:
  go-build-cache:
